name: Build App
run-name: Build App
on: [push]
jobs:
  MacOS-Build-Actions:
    runs-on: macOS-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
          flutter-version: 3.x
      - run: flutter --version

