name: Build App
run-name: Build App
on: [push]
jobs:
  MacOS-Build-Actions:
    runs-on: macos-latest
    steps:
        - name: Clone repository
          uses: actions/checkout@v4
        - name: Set up Flutter
          uses: subosito/flutter-action@v2
          id: flutter-action
          with:
            channel: stable
        - run: flutter build macos
        - run: mkdir ~/dist/ && zip ~/dist/BqScreenshot-${{steps.flutter-action.outputs.VERSION}}.zip build/macos/Build/Products/Release/bq_screenshot.app
        - name: save Artifacts
          uses: actions/upload-artifact@v3
          with:
            name: Build
            path: ~/dist
        - run: ls -la ~/dist
