name: Build App
run-name: Build App
on: [push]
jobs:
#  MacOS-Build-Actions:
#    runs-on: macos-latest
#    steps:
#        - name: Clone repository
#          uses: actions/checkout@v4
#        - name: Set up Flutter
#          uses: subosito/flutter-action@v2
#          id: flutter-action
#          with:
#            channel: stable
#        - run: flutter pub get
#        - run: flutter pub upgrade
#        - run: flutter build macos --release
#        - run: mkdir ~/dist/ && mv build/macos/Build/Products/Release/bq_screenshot.app ~/dist/
#        - name: save Artifacts
#          uses: actions/upload-artifact@v3
#          with:
#            name: BuildMacOS
#            path: ~/dist

  Windows-Build-Actions:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter pub upgrade
      - run: flutter build windows --release
      - run: mkdir ~/dist/ && mv build\windows\x64\runner\Release\bq_screenshot.exe ~/dist/
      - name: save Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BuildWindows
          path: ~/dist